name: Compress JPG/PNG to WEBP and Deploy

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  compress_upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Set up ImageMagick
        run: |
          sudo apt-get update
          sudo apt-get install -y imagemagick
      - name: Compress JPG and PNG to WEBP
        run: |
          mkdir -p webp
          shopt -s nullglob
          for img in *.jpg *.jpeg *.png; do
            if [ -f "$img" ]; then
              convert "$img" -resize 800x -quality 80 "webp/${img%.*}.webp"
            fi
          done
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./webp
          publish_branch: gh-pages
